/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * alova - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'user.get_user_profile': ['GET', '/user/profile'],
  'user.post_posts': ['POST', '/posts'],
  'order.get_demo': ['GET', '/demo']
};
