/* tslint:disable */
/* eslint-disable */
/**
 * alova - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

declare global {
  interface Apis {
    user: {
      /**
       * ---
       *
       * [GET] 获取用户信息
       *
       * **path:** /user/profile
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   username: string
       *   email: string
       * }
       * ```
       */
      get_user_profile<
        Config extends Alova2MethodConfig<{
          username: string;
          email: string;
        }>
      >(
        config?: Config
      ): Alova2Method<
        {
          username: string;
          email: string;
        },
        'user.get_user_profile',
        Config
      >;
      /**
       * ---
       *
       * [POST] post
       *
       * **path:** /posts
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   name?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   name: string
       * }
       * ```
       */
      post_posts<
        Config extends Alova2MethodConfig<{
          name: string;
        }> & {
          params: {
            name?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          name: string;
        },
        'user.post_posts',
        Config
      >;
    };
    order: {
      /**
       * ---
       *
       * [GET] demo
       *
       * **path:** /demo
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_demo<Config extends Alova2MethodConfig<object>>(
        config?: Config
      ): Alova2Method<object, 'order.get_demo', Config>;
    };
  }

  var Apis: Apis;
}
